name: Python Quiz Beginner
description: Beginner Level Quiz for the Python Language
title: "Python Quiz Beginner:"
assignees:
  - GamerSoft24
  - SutoEXEC
  - Okmeque1
body:
  - type: markdown
    attributes:
      value: |
        "Thanks for taking the time to complete this quiz!"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you when your quiz has been evaluated?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: call_func
    attributes:
      label: How to call a function (1 option to select)?
      multiple: false
      options:
        - call func_name()
        - import func_name()
        - func_name()
        - func_name
      validations:
        required: true
  - type: dropdown
    id: input_and_print_str_int_float
    attributes:
      label: How to make the user input and print text, integers or decimals (2 options to select)?
      multiple: true
      options:
        - print(Hello World)
        - input("Hello World")
        - input(Hello World
        - print("Hello World")
        - print "Hello World"
        - input "Hello World"
      validations:
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GamerSoft24/Software/blob/Main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
